export const REQUEST_SUCCESS = 1000;
export const ERROR_502 = 502;
export const ERROR_404 = 404;
export const ERROR_401 = 401;

export const typeName = {
  SWITCH_ENVIRONMENT: "SWITCH_ENVIRONMENT",

  SHOW_LOADING: "SHOW_LOADING",
  HIDE_LOADING: "HIDE_LOADING",
  UPLOAD_FILE: "UPLOAD_FILE",

  GET_BANNERS_HOME: "GET_BANNERS_HOME",
  GET_BOOK_LIST: "GET_BOOK_LIST",
  GET_BOOK_LIST_FLASH_SALE: "GET_BOOK_LIST_FLASH_SALE",

  ADD_BOOK_TO_CART: "ADD_BOOK_TO_CART",
  REMOVE_BOOK_TO_CART: "REMOVE_BOOK_TO_CART",
  DECREASE_BOOK_TO_CART: "DECREASE_BOOK_TO_CART",
  EDIT_QUANTITY_BOOK_TO_CART: "EDIT_QUANTITY_BOOK_TO_CART",
};
